AMP-43407 add support for amplitude plugin support
iterativelyhq/itly-sdk pull request #134
Opened 2021-10-09 22:46 UTC by qingzhuozhen

samples in https://bitbucket.org/seasyd/analytics_tools/pull-requests/80/feat-update-examples-for-browser-and-node

2021-10-10 22:48 UTC, justin-fiedler requested changes

2021-10-10 22:48 UTC, justin-fiedler commented on packages/plugin-amplitude-node/lib/index.ts
> +    if (!groupType) {
logger.warn(`Amplitude group() skipped. Missing required groupType property.`);

2021-10-10 22:48 UTC, justin-fiedler commented on packages/plugin-amplitude-node/lib/index.ts
> +    const groupType = properties && properties.groupType ? properties.groupType : undefined;
What about using `groupId` for `groupType`. Group names could first check for `AmplitudeCallOptions.groupName` and fallback to `Event.groupName` . This lets the user config in Stargate or in code for custom mapping. We should log a warning if no value is found.

For example our Stargate tracking plan. We have ~10 properties on Group. `orgId` is optional and strongly typed as a string ,we also want to use it to set the `groupName` for Amplitude.

Notice I am using browser syntax here just to show how groupName would work with arrays and strings.
```
// orgId property is validated as a tracking plan Group traits and mapped to groupName for Amplitude via CallOptions. This lets the user do their own amplitude specific mapping.

itly.group('orgId',  { orgId: '15' }, { amplitude: { groupName: '15' } });
```

We could make this easier by adding `groupName` property in the tracking plan as an Array with item type string. Which would automatically set in Amplitude. Unfortunately we don't support union types in Stargate so the type has to be Array to support both usages.
```
// We could update the tracking plan to have `groupNames` as optional on Group traits
itly.group('orgId',  { orgId: '15' , groupName: ['15'] });
itly.group('sport',  { groupName: ['soccer', 'tennis'] });

// Still allow overrides specific to Amplitude if needed
itly.group('sport',  { groupName: ['soccer', 'tennis']}, { amplitude: { groupName: 'collegiate' });
```

Given the difference between values in the platforms. We can make the Browser `AmplitudeGroupCallOptions.groupName:string|string[]` and for Node `AmplitudeGroupCallOptions.groupName:string`

2021-10-11 05:38 UTC, qingzhuozhen commented on packages/plugin-amplitude-node/lib/index.ts
> +    const groupType = properties && properties.groupType ? properties.groupType : undefined;
@justin-fiedler That seems a good way to support group for amplitude, and one concern here is if the customer have other plugins, for example segment, the groupId will be considered as group name, and I guess segment doesn't have a group type same as in amplitude. Would we need to align this for different plugins? I guess when we call `itly.group` it will call `group` method in each plugin

2021-10-11 15:33 UTC, justin-fiedler commented on packages/plugin-amplitude-node/lib/index.ts
> +    const groupType = properties && properties.groupType ? properties.groupType : undefined;
@qingzhuozhen good point. I read through the docs some more for both Segment and Amplitude and am now thinking we ignore `groupId` and by default use the Group traits as `groupType`:`groupName` pairs and call amplitude.setGroup() for each. We can add a check if the trait is a supported type and log a warning if it's not.

```
const identifyObject = new Identify();
Object.entries(groupProperties).forEach([key, value] => {
  // if value is not supported type log a warning and skip setting it
  identifyObject.setGroup(groupType, groupId);
})
```

This should work with our current tracking plan and play nice with segment and other plugins.
```
itly.group(someGroupIdUsedByOtherPlugins, { orgId: '15', orgName: 'My Org'})
```

I think we should also expose groups somehow on AmplitudeGroupOptions. To support setting multiple values a dictionary could be nice (similar to HTTP v2 API).
```
itly.group(someGoupId, {}, { amplitude: { groups: { 'org id': '15', 'org name': 'My Org' }});
``

2021-10-11 17:35 UTC, qingzhuozhen commented on packages/plugin-amplitude-node/lib/index.ts
> +    const groupType = properties && properties.groupType ? properties.groupType : undefined;
@justin-fiedler This sounds good. I am ok to ignore the groupId and groupProperties here, and use the AmplitudeGroupOptions. This should not affect other plugins like segment, and in future we can use groupId and groupProperties for `groupIdentify` function. Let me try to extend AmplitudeGroupOptions to support it.

2021-10-12 04:24 UTC, justin-fiedler requested changes

2021-10-12 04:24 UTC, justin-fiedler commented on packages/plugin-amplitude-node/lib/index.ts
> +    [name: string] : string | string[]
I think Node only supports `{ [name: string] : string }` so I think its ok that we make this string only. https://github.com/amplitude/Amplitude-Node/blob/a3f6b173a6884cb11168b6d09ae3d0351533c34a/packages/identify/src/identify.ts#L87

2021-10-12 05:27 UTC, qingzhuozhen commented on packages/plugin-amplitude-node/lib/index.ts
> +    [name: string] : string | string[]
Great, just one the update

2021-10-12 15:24 UTC, justin-fiedler approved these changes

2021-10-12 15:25 UTC, justin-fiedler commented
@qingzhuozhen looks good. Merge when ready (it's still a draft PR).

2021-10-12 17:39 UTC, merged