fix: enum ValidationOptions
iterativelyhq/itly-sdk pull request #45
Opened 2021-03-05 13:42 UTC by falconandy

2021-03-06 00:36 UTC, justin-iteratively requested changes

2021-03-06 00:36 UTC, justin-iteratively commented on packages/sdk/lib/base.ts
> +export enum ValidationOptions {
Please rename `ValidationOptions` => `Validation`

2021-03-06 00:36 UTC, justin-iteratively commented on packages/sdk/lib/base.ts
> +  private validationOptions = DEFAULT_DEV_OPTIONS.validation;
Please rename `validationOptions` => `validation`

2021-03-08 11:56 UTC, falconandy commented on packages/sdk/lib/base.ts
> +export enum ValidationOptions {
Renamed

2021-03-08 17:57 UTC, justin-iteratively approved these changes

2021-03-08 20:27 UTC, merged